# Generated by Django 6.0.4 on 2026-04-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(default='Default', max_length=60)),
                ('percent_by_class', models.JSONField(help_text='e.g. {"EQUITY": 55, "BONDS_DEBT": 20, "GOLD": 10, "ALTERNATIVES": 10, "REAL_ESTATE": 5}')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EQUITY', 'Stocks & Equity'), ('GOLD', 'Gold & Silver'), ('BONDS_DEBT', 'Bonds & Debt'), ('REAL_ESTATE', 'Real Estate'), ('RETIREMENT', 'Retirement'), ('CASH', 'Cash & Savings'), ('ALTERNATIVES', 'Alternatives'), ('OTHER', 'Other')], max_length=20)),
                ('subtype', models.CharField(help_text='e.g. DIRECT_STOCK, FD, PPF', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('geography', models.CharField(blank=True, choices=[('IN', 'India'), ('INTL', 'International'), ('MIXED', 'Mixed')], max_length=10, null=True)),
                ('sub_class', models.CharField(blank=True, default='', max_length=40)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('live_price_enabled', models.BooleanField(default=False)),
                ('instrument_symbol', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('exclude_from_allocation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('is_exempt', models.BooleanField(default=False, help_text='If true, transactions in this category are excluded from totals.')),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='EssentialsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_fund_target_months', models.IntegerField(default=6)),
                ('term_cover_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('term_cover_target_multiplier', models.IntegerField(default=10, help_text='target = annual_income * multiplier')),
                ('health_cover_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('health_cover_target', models.DecimalField(decimal_places=4, default=1000000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_id', models.CharField(blank=True, default='', help_text='Optional preset key, e.g. "RETIREMENT" or "EMERGENCY".', max_length=40)),
                ('target_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('target_date', models.DateField()),
                ('linked_asset_class', models.CharField(default='NET_WORTH', help_text='e.g. "NET_WORTH", "EQUITY", or a custom class id.', max_length=40)),
                ('linked_asset_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='e.g. "generic_csv", "zerodha" (Phase 6+).', max_length=40)),
                ('scope', models.CharField(help_text='"assets" | "transactions"', max_length=20)),
                ('mode', models.CharField(help_text='"append" | "update_by_name"', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('rows_imported', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'OK'), ('error', 'Error')], max_length=10)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HOME_LOAN', 'Home Loan'), ('VEHICLE_LOAN', 'Vehicle Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('EDUCATION_LOAN', 'Education Loan'), ('CREDIT_CARD', 'Credit Card'), ('GOLD_LOAN', 'Gold Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('FRIENDS_FAMILY', 'Friends / Family'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('outstanding_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('monthly_emi', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_json', models.JSONField()),
                ('cadence', models.CharField(help_text='e.g. "monthly", "weekly", or a CRON.', max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10)),
                ('base_currency', models.CharField(max_length=3)),
                ('net_worth', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_assets', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_liabilities', models.DecimalField(decimal_places=4, max_digits=20)),
                ('breakdown_json', models.JSONField(help_text='Serialized allocation/holdings at snapshot time.')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='fxrate',
            name='core_fxrate_user_id_bc38e1_idx',
        ),
        migrations.AlterField(
            model_name='fxrate',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(fields=('user', 'from_ccy', 'to_ccy'), name='uniq_fx_pair_per_user'),
        ),
        migrations.AddField(
            model_name='allocationtarget',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_targets', to='core.profile'),
        ),
        migrations.AddField(
            model_name='asset',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.profile'),
        ),
        migrations.AddField(
            model_name='category',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='NULL = system default (shared across profiles).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.profile'),
        ),
        migrations.AddField(
            model_name='essentialsstate',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='essentials', to='core.profile'),
        ),
        migrations.AddField(
            model_name='goal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.profile'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='core.profile'),
        ),
        migrations.AddField(
            model_name='liability',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='core.profile'),
        ),
        migrations.AddField(
            model_name='recurringrule',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='core.profile'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.profile'),
        ),
        migrations.AddField(
            model_name='tag',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.profile'),
        ),
        migrations.AddField(
            model_name='liability',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='liabilities', to='core.tag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='core.tag'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.profile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.recurringrule'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='core.tag'),
        ),
        migrations.AddConstraint(
            model_name='allocationtarget',
            constraint=models.UniqueConstraint(fields=('profile', 'preset_name'), name='uniq_alloc_preset_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('profile', 'type', 'name'), name='uniq_category_per_scope'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['profile', 'taken_at'], name='core_snapsh_profile_7cfdfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('profile', 'label'), name='uniq_tag_per_profile'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['profile', 'category'], name='core_asset_profile_8826a0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['profile', 'date'], name='core_transa_profile_071dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['profile', 'category'], name='core_transa_profile_c42535_idx'),
        ),
    ]
