# Generated by Django 6.0.4 on 2026-04-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allocationtarget_asset_category_essentialsstate_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geography',
            field=models.CharField(blank=True, choices=[('IN', 'India'), ('INTL', 'International'), ('MIXED', 'Mixed')], default='', max_length=10),
        ),
    ]
