# Generated by Django 6.0.4 on 2026-04-19 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_asset_geography'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_key', models.CharField(choices=[('zerodha', 'Zerodha'), ('chola', 'Cholamandalam Securities'), ('aionion', 'Aionion')], max_length=20)),
                ('account_label', models.CharField(help_text='Free-form label disambiguating multiple accounts with the same broker.', max_length=80)),
                ('client_code', models.CharField(blank=True, default='', max_length=40)),
                ('base_currency', models.CharField(default='INR', max_length=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(blank=True, default='', max_length=12)),
                ('exchange_symbol', models.CharField(blank=True, default='', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('STOCK', 'Equity stock'), ('MF', 'Mutual fund')], max_length=8)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('amfi_code', models.CharField(blank=True, default='', max_length=12)),
                ('mf_scheme_code', models.CharField(blank=True, default='', max_length=20)),
                ('isin_aliases', models.JSONField(blank=True, default=list, help_text='List of prior ISINs for this instrument after corp actions.')),
                ('needs_review', models.BooleanField(default=False, help_text='Set when auto-created from Asset backfill without a confirmed ISIN.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('pay_date', models.DateField(blank=True, help_text='Date cash hit the bank; may be unknown (e.g. Zerodha XLSX only gives ex-date).', null=True)),
                ('amount_gross', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tds', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount_net', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dividend_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('source', models.CharField(choices=[('zerodha_xlsx', 'Zerodha XLSX'), ('chola_pdf', 'Chola PDF'), ('manual', 'Manual'), ('amfi_idcw', 'AMFI IDCW feed')], max_length=20)),
                ('raw_row_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividend_records', to='core.brokeraccount')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividend_records', to='core.importjob')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_records', to='core.profile')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_records', to='core.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SPLIT', 'Stock split'), ('BONUS', 'Bonus issue'), ('MERGER', 'Merger'), ('BUYBACK', 'Buyback'), ('DEMERGER', 'Demerger'), ('ISIN_CHANGE', 'ISIN change')], max_length=16)),
                ('ex_date', models.DateField()),
                ('ratio_numerator', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('ratio_denominator', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('units_added', models.DecimalField(blank=True, decimal_places=8, help_text='When the source reports added qty directly (Chola-style SPLIT).', max_digits=20, null=True)),
                ('cash_component', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_account', models.ForeignKey(blank=True, help_text='Only set when the action row is specific to one account (e.g. Chola SPLIT).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_actions', to='core.brokeraccount')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='core.profile')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='core.instrument')),
                ('new_instrument', models.ForeignKey(blank=True, help_text='For MERGER / DEMERGER / ISIN_CHANGE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_actions_as_new', to='core.instrument')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='Links equity / MF assets to the canonical Instrument row driving XIRR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.instrument'),
        ),
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('source', models.CharField(choices=[('nse_bhavcopy', 'NSE bhavcopy'), ('bse_bhavcopy', 'BSE bhavcopy'), ('amfi', 'AMFI NAV feed'), ('manual', 'Manual')], max_length=20)),
                ('as_of', models.DateField(help_text='Business date the price applies to.')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ticks', to='core.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('exec_time', models.DateTimeField(blank=True, help_text='Intra-day order execution time for FIFO tie-breaking.', null=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('brokerage', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('stt', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('gst', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('stamp_duty', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sebi_charges', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('exchange_charges', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_charges', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=4, help_text='Signed cashflow: BUY is negative, SELL is positive.', max_digits=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('off_market', models.BooleanField(default=False)),
                ('trade_ref', models.CharField(max_length=80)),
                ('raw_row_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_trades', to='core.brokeraccount')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_trades', to='core.importjob')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_trades', to='core.instrument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_trades', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_price_enabled', models.BooleanField(default=False)),
                ('last_price_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['profile', 'broker_key'], name='core_broker_profile_5eebd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokeraccount',
            constraint=models.UniqueConstraint(fields=('profile', 'broker_key', 'account_label'), name='uniq_broker_account_per_profile'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['profile', 'kind'], name='core_instru_profile_c64cec_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['profile', 'exchange_symbol'], name='core_instru_profile_5e9e98_idx'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(condition=models.Q(('isin__gt', '')), fields=('profile', 'isin'), name='uniq_instrument_isin_per_profile'),
        ),
        migrations.AddIndex(
            model_name='dividendrecord',
            index=models.Index(fields=['profile', 'ex_date'], name='core_divide_profile_4e64d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='dividendrecord',
            constraint=models.UniqueConstraint(fields=('profile', 'instrument', 'ex_date', 'amount_gross'), name='uniq_dividend_per_ex_date'),
        ),
        migrations.AddIndex(
            model_name='corporateaction',
            index=models.Index(fields=['instrument', 'ex_date'], name='core_corpor_instrum_8c855a_idx'),
        ),
        migrations.AddConstraint(
            model_name='corporateaction',
            constraint=models.UniqueConstraint(fields=('instrument', 'action_type', 'ex_date'), name='uniq_corp_action_per_instrument_date'),
        ),
        migrations.AddIndex(
            model_name='pricetick',
            index=models.Index(fields=['instrument', '-as_of'], name='core_pricet_instrum_0e9240_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricetick',
            constraint=models.UniqueConstraint(fields=('instrument', 'source', 'as_of'), name='uniq_price_tick_per_instrument_source_date'),
        ),
        migrations.AddIndex(
            model_name='stocktrade',
            index=models.Index(fields=['profile', 'trade_date'], name='core_stockt_profile_5cf044_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktrade',
            index=models.Index(fields=['broker_account', 'instrument', 'trade_date'], name='core_stockt_broker__d854a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktrade',
            constraint=models.UniqueConstraint(fields=('broker_account', 'trade_ref'), name='uniq_trade_ref_per_broker_account'),
        ),
    ]
