# Generated by Django 6.0.4 on 2026-04-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_aionion_dividend_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='pan',
            field=models.CharField(blank=True, default='', help_text='Indian PAN of the account holder. Used to group FY-wise capital gains for ITR filing.', max_length=10),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='pan_holder_name',
            field=models.CharField(blank=True, default='', help_text="Friendly label for the PAN holder (e.g. 'Self', 'Mom').", max_length=80),
        ),
    ]
